version: '3'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 2015:2015
    networks:
      - caddy
    command: -email email@caddy-docker-demo -agree=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 3
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

volumes:
  caddy:
    driver: rexray/efs

networks:
  caddy:
    driver: overlay